import { SkillType } from './interface';

export const Ahli: SkillType = {
  Bash: {
    name: 'Bash',
    logo: '/public/skills/bash.svg',
    link: 'https://www.gnu.org/software/bash/',
    color: '#4EAA25',
  },
  CPlusPlus: {
    name: 'C++',
    logo: '/public/skills/cplusplus.svg',
    link: 'https://isocpp.org/',
    color: '#00599C',
  },
  Canva: {
    name: 'Canva',
    logo: '/public/skills/canva.svg',
    link: 'https://www.canva.com/',
    color: '#00C4CC',
  },
  Dart: {
    name: 'Dart',
    logo: '/public/skills/dart.svg',
    link: 'https://dart.dev/',
    color: '#0175C2',
  },
  Django: {
    name: 'Django',
    logo: '/public/skills/django.svg',
    link: 'https://www.djangoproject.com/',
    color: '#092E20',
  },
  Docker: {
    name: 'Docker',
    logo: '/public/skills/docker.svg',
    link: 'https://www.docker.com/',
    color: '#2496ED',
  },
  Figma: {
    name: 'Figma',
    logo: '/public/skills/figma.svg',
    link: 'https://www.figma.com/',
    color: '#F24E1E',
  },
  Firebase: {
    name: 'Firebase',
    logo: '/public/skills/firebase.svg',
    link: 'https://firebase.google.com/',
    color: '#FFCA28',
  },
  Flutter: {
    name: 'Flutter',
    logo: '/public/skills/flutter.svg',
    link: 'https://flutter.dev/',
    color: '#02569B',
  },
  Excel: {
    name: 'Excel',
    logo: '/public/skills/excel.svg',
    link: 'https://www.microsoft.com/en-us/microsoft-365/excel',
    color: '#217346',
  },
  Java: {
    name: 'Java',
    logo: '/public/skills/java.svg',
    link: 'https://www.java.com/',
    color: '#5382A1',
  },
  JavaScript: {
    name: 'JavaScript',
    logo: '/public/skills/javascript.svg',
    link: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript',
    color: '#F7DF1E',
  },
  Kotlin: {
    name: 'Kotlin',
    logo: '/public/skills/kotlin.svg',
    link: 'https://kotlinlang.org/',
    color: '#0095D5',
  },
  MongoDB: {
    name: 'MongoDB',
    logo: '/public/skills/mongodb.svg',
    link: 'https://www.mongodb.com/',
    color: '#47A248',
  },
  NextJS: {
    name: 'Next.js',
    logo: '/public/skills/nextjs.svg',
    link: 'https://nextjs.org/',
    color: '#000000',
  },
  NodeJS: {
    name: 'Node.js',
    logo: '/public/skills/nodejs.svg',
    link: 'https://nodejs.org/',
    color: '#339933',
  },
  Python: {
    name: 'Python',
    logo: '/public/skills/python.svg',
    link: 'https://www.python.org/',
    color: '#3776AB',
  },
  React: {
    name: 'React',
    logo: '/public/skills/react.svg',
    link: 'https://reactjs.org/',
    color: '#61DAFB',
  },
  TailwindCSS: {
    name: 'Tailwind CSS',
    logo: '/public/skills/tailwindcss.svg',
    link: 'https://tailwindcss.com/',
    color: '#38B2AC',
  },
  TensorFlow: {
    name: 'TensorFlow',
    logo: '/public/skills/tensorflow.svg',
    link: 'https://www.tensorflow.org/',
    color: '#FF6F00',
  },
  TypeScript: {
    name: 'TypeScript',
    logo: '/public/skills/typescript.svg',
    link: 'https://www.typescriptlang.org/',
    color: '#007ACC',
  },
  Ubuntu: {
    name: 'Ubuntu',
    logo: '/public/skills/ubuntu.svg',
    link: 'https://ubuntu.com/',
    color: '#E95420',
  },
  ViteJS: {
    name: 'Vite.js',
    logo: '/public/skills/vitejs.svg',
    link: 'https://vitejs.dev/',
    color: '#646CFF',
  },
  VSCode: {
    name: 'Visual Studio Code',
    logo: '/public/skills/vscode.svg',
    link: 'https://code.visualstudio.com/',
    color: '#007ACC',
  },
};
